### ISSUE TITLE
Service 섹션에 들어 갈 내용 정리 함께해요

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#10]

**Comment by takearest118** [comment]
@rjkorea/dev On/Off LIne Ticket Solution, Richard&Friends, Media&Production 부분 얘기하는거에요?

**Comment by rj-kelly-kim** [comment]
해당 issue는 closed 하고 @youlim90 가 새로 생성한 issue_#21 로 진행하겠습니다.
