### ISSUE TITLE
TFC2017 운영 결과 보고서 Inforgraphic 작업

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#110]
TFC2017 운영 결과 보고서는 
아래 보고서 및 자료 준비 후 
금주내 VU Ent. 와 대면 미팅을 진행할 예정입니다.

- Inforgraphic Ver.의 Insight 내용 정리
-  Admin > Home 통계
- 매출 정산서

**Comment by rj-kelly-kim** [comment]
Inforgraphic 1차 정리해 공유 드립니다.
https://drive.google.com/open?id=0B5-RhNWlZZVeWVdsRXg3X2N1M3c

**Comment by takearest118** [comment]
@rj-kelly-kim 권한이 없다고 합니다

**Comment by rj-kelly-kim** [comment]
@takearest118 내일 VU와 미팅에서 진행할 TKIT Admin 주소 확인 부탁드립니다.

**Comment by rj-kelly-kim** [comment]
금일 VU와 미팅으로 해당 이슈는 closed 하며,
차주 (1/19)목요일 레인보우 페스티벌 관련 회의가 예정 되어 있습니다.
