### ISSUE TITLE
Tech Crunch Meetup Pichoff 준비 

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#13]
Tech Crunch Meetup Pichoff 신청 진행.

**Comment by takearest118** [comment]
https://techcrunch.com/event-info/meetup-pitch-off-seoul-2016/?utm_medium=partnerad&utm_campaign=seoulmeetup&utm_source=besuccess

**Comment by rj-kelly-kim** [comment]
외부 사람에게 비즈니스의 전반을 이해시키며 f&a까지 역할을 맡기기엔 현실적으로 어려움이 있음 확인.
Tech Crunch meetup-day는 비정기적으로 진행 됨으로
그 사이 우리는 '영어 실력 향상' 혹은 '영어 스피치가 되는' 멤버를 만들어 
다음 meet-up pitch off 행사를 대응 합니다. 
(가장 유력한 후보는 @youlim90 !!)
