### ISSUE TITLE
티켓 초대권 (Plug-in) 셋팅 요청

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#14]
워드프레스의 플러그인을 활용 
티켓 초대권 등록 프로세스 적용을 요청 드립니다. 

티켓 초대권으로 필요한 정보는 아래와 같습니다. 

**[필수 정보]**

- 이름
- 생년월일
- 전화 번호
- 참석 날짜

**Comment by takearest118** [comment]
@rjkorea/dev 일단 제가 http://tickera.com 플러그인을 이용하여 데모를 만들어 보고 피드백 드리도록 하겠습니다.

**Comment by rj-kelly-kim** [comment]
참고로, 
참석 날짜의 경우 아래와 같은 3가지로 구분이 될 수 있습니다.

- 양일 모두 참석
- 토요일 참석
- 일요일 참석

**Comment by takearest118** [comment]
@rjkorea/dev payment 부분에서 정상적으로 작동하지 않아 보류

**Comment by rj-kelly-kim** [comment]
네. 확인 감사합니다
해당 이슈는 closed 하겠습니다.
