### ISSUE TITLE
SFF 2016 컴퍼니 부스 리뷰

### ISSUE THREAD

**Issue by takearest118** [rjkorea/avocado#15]
## 컴퍼니 부스(초대권 담당)
2016 10월 15일 토요일
2016 10월 16일 일요일

## 리소스
노트북 4대
포스기계 2대
인원 7명

## 환경부담금
카드 결제, 현금 가능

## 프로세스
신분증을 통하여 신원인증
환경부담금
밴드착용 (1day, 2day, vip)
입장

## 기타사항
- 구글드라이브 엑셀 파일을 이용하여 초대권 리스트 관리(공유기능을 이용하여 관리하는 듯)
- 트랜잭션 문제 어떻게 처리하나?
- 엑스페리아 야광봉 인스타그램 인증샷 이벤트
- 쓰레기문제: 이벤트 야광봉으로인한 다량의 쓰레기 발생, 밴딩 스티커

## 개선사항
구글 드라이브를 이용한 초대권 리스트 관리 프로세스를 웹기반으로 시스템화 하는 작업
- 신청폼
- 관리자
- 모니터링

실제로 스탭이되어서 일를 해보는 것

**Comment by rj-kelly-kim** [comment]
수고 많으셨습니다. 해당 내용은 아래 wiki로 정리 완료하였습니다.
https://github.com/rjkorea/avocado/wiki/SFF-2016-Ticketing-%ED%98%84%EC%9E%A5-%EA%B4%80%EC%B0%B0-%EB%82%B4%EC%9A%A9
