### ISSUE TITLE
2016 SFF 일반 티켓 교환처

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#19]
-현장운영인력 : 6~7명

-관련장비 : 없음

-프로세스 : 종이티켓으로 1,2일 권 확인 > 신분증 19세 인증 > 밴딩

-참고내용 : 1)외국인 입장객에게 가이드가 전달되지않음. 2)페이스북 생년월일로 성인인증 3)같이 온 친구 신분증 인증

**Comment by rj-kelly-kim** [comment]
수고 많으셨습니다. 해당 내용은 아래 wiki로 정리 완료하였습니다.
https://github.com/rjkorea/avocado/wiki/SFF-2016-Ticketing-%ED%98%84%EC%9E%A5-%EA%B4%80%EC%B0%B0-%EB%82%B4%EC%9A%A9
