### ISSUE TITLE
[Back-end] Information Architectuer

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#26]
(UI/Front-end)

**Comment by rj-kelly-kim** [comment]
Front-end 단의 IA 내용 정리해 공유 드립니다. (아래 링크 확인 요청)

https://docs.google.com/spreadsheets/d/1sbn5mlsnkBTfvcMC3owwpeSw1s1eNVT_Xm7zXvAyTCs/edit#gid=1136729006

**Comment by rj-kelly-kim** [comment]
이후 IA 는 @takearest118 이 모델링과 함께 구현 방향에 대해 최종 점검을 진행합니다. 

@takearest118  IA/모델링 방향 정리 후, 내용을 공유 주시면, 
해당 내용을 토대로 Front단 Wireframe 설계 작업을 진행하겠습니다.

**Comment by takearest118** [comment]
#25 데이터 모델링 이슈입니다.

**Comment by takearest118** [comment]
@rj-kelly-kim @youlim90 일단 기본적인 데이터 모델링은 완료 하였습니다.

**Comment by rj-kelly-kim** [comment]
Back-end 단의 IA task는 Close 하며, 
Front단의 IA 별도 생성하여 진행하도록 하겠습니다.

**Comment by takearest118** [comment]
@rj-kelly-kim 네 알겠습니다
