### ISSUE TITLE
홈페이지 컨텐트 정리 

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#33]
- SERVICE / OUR TEAM 소개 내용
- KELLY 정리해주실 내용 11/1 까지 업데이트 예정

**Comment by rj-kelly-kim** [comment]
서비스 소개 내용은 B2B적 관점으로 RJ Ent. 의 솔루션/인프라를 설명한 내용입니다.  
아래 해당 내용을 영문화 하여 홈페이지 적용 요청 드립니다. 


[서비스 소개] - 한글 - 

O2O TICKET SOLUTION
----------------------------------
새로운 고객 확보를 통한 티켓 세일링
혁신적인 기술을 통한 티켓팅 및 솔루션 제공


RICHARD & FRIEND
----------------------------------
글로벌 리더들과 다양한 액티비티 환경에서 지식과 경험을 함께 나누는 지식네트워크파티


PRODUCTION & MEDIA
----------------------------------
글로벌 대형 행사 제작/운영이 가능한 전문 프로덕션 인프라 보유
TV CF, 다큐멘터리, 브랜딩 등 전문 영상 기획/제작 인프라 보유

**Comment by rj-kelly-kim** [comment]
우선 프로필 영역을 제외한 나머지 섹션에 대한 작업 완료를 요청 드립니다.
