### ISSUE TITLE
Wireframe 작업

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#37]
---
- Flowchart
- Front IA 
- UI 화면 설계

**Comment by rj-kelly-kim** [comment]
Wireframe 문서 정리해 공유 드립니다. 
내일 리뷰 미팅 전 충분히 확인해주시기 바랍니다. 
https://drive.google.com/drive/folders/0B5-RhNWlZZVeRnRBejB0a0NvLUU

**Comment by rj-kelly-kim** [comment]
MVP가 재 설정되었습니다. 

해당  Issue Task는  closed 하지 않고 계속 유지하며
앞으로 있을 TKIT Wireframe 은 
본 issue에 이어서 업데이트 하도록 하겠습니다.  (히스토리 관리 차원)

**Comment by takearest118** [comment]
이 이슈의 마일스톤 설정은 일단 해제하겠습니다.

**Comment by rj-kelly-kim** [comment]
오래된 Task는 closed 하고 
wireframe 작업 재 시작시 새로운 이슈 생성으로 진행하겠습니다.
