### ISSUE TITLE
http://www.tkit.me 1차 Pre-Site 구축

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#45]
http://www.tkit.me 도메인의 
Pre-site 운영을 아래 2 step 으로 나눠 사이트 오픈을 준비 합니다. 

Step.1
------------------------
1) 목적 : TKIT 서비스의 존재감 및 형태 알림
2) 컨셉 : 기대감, 신비감, 궁금증 유발
3) 리소스 : IMG
4) Due : TFC 2017 행사 전까지

Step.2
------------------------
1) 목적 : TKIT 의 세부 비즈니스 포인트 및 서비스 내용 소개
2) 컨셉 : TKIT 비즈니스 & 브랜드 사이트
3) 리소스 : html, css, store 연동 등 site 전반 구축
4) Due : 비즈니스 전략 진행 사항에 따라 협의

-----------------------------------------------------
관련해서,
Step.1 준비를 위해 노출 정보와 컨셉은 제가 잡아 공유 드리도록 하겠습니다.
본  task의 최종 마무리는 @youlim90 완료해주세요

**Comment by takearest118** [comment]
@rj-kelly-kim @youlim90 아래 2개 템플릿 사용하여 수정하면 좋을것 같습니다.
> http://rjkorea.s3-website.ap-northeast-2.amazonaws.com
> http://rjkorea-home.s3-website.ap-northeast-2.amazonaws.com

**Comment by rj-kelly-kim** [comment]
http://www.tkit.me 구글 로그 추적 코드 아래와 같이 전달 드립니다. 

- 추적 ID : UA-88009429-1

- 추적 스크립트
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88009429-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by youlim90** [comment]
Grace 코딩 시작 11월25일
