### ISSUE TITLE
VU Ent. TKIT 적용 범위 공유 / 초대권 리스트 양식 전달

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#63]
VU Ent. 에 TKIT의 적용 범위를 공유하며, 
초대권 리스트 양식을 Google Drive 로 공유하도록 하겠습니다. 

@takearest118 
---------------------------
-> VU Ent.에 공유 될 초대권 양식 정리 부탁 드립니다.

해당 공유는 2016.12.01에 진행도록 하겠습니다.

**Comment by takearest118** [comment]
초대권 리스트 포멧은 #61 이슈에서 진행 중

**Comment by rj-kelly-kim** [comment]
네~!

**Comment by rj-kelly-kim** [comment]
https://docs.google.com/spreadsheets/d/1IC_dtf4p5Bh8Gd6LyCi5dxEsWqPjFa88Uy1SxQFSKXk/edit#gid=0

위 링크로 실시간 리스트업 진행. 
VU Ent. 외 절대! 위 리스트 편집 불가 입니다.

**Comment by rj-kelly-kim** [comment]
프로모션 당첨자 세부 정보 요청 필요 (vu 에 확인 필요)
