### ISSUE TITLE
TKIT ipad icon

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#68]
https://drive.google.com/drive/folders/0Bxrqc_lAj5EPRUMyY2F3NUNJMXc

**Comment by rj-kelly-kim** [comment]
@youlim90 해당 issue task는
 테블릿 디자인 전반에 대한 작업으로  issue 작업 범위를 수정하는 것이 좋겠습니다. (issue 네이밍 조정 필요) 

금주 까지 HJ와 함께 테블릿 전반에 대한 디자인 수정 작업을 완료 해주세요 
(수정/조정이 필요한 사항 list up 해 HJ에게 일괄 작업 요청.)
