### ISSUE TITLE
SMS 일괄 발송 작업

### ISSUE THREAD

**Issue by takearest118** [rjkorea/avocado#79]
~~AWS 매달 100만건 무료~~ 서울리젼에서 지원하지 않음
3rd 파티 업체에서 선택하여 엑셀 파일 형식으로 전송하는 방식으로 @rj-kelly-kim 가 진행

**Comment by rj-kelly-kim** [comment]
SMS 발송은
초대권 업데이트 일정 확인/참고 후
가비아 SMS 플랫폼을 통해 
'티켓 교부 안내 방식' 의 내용으로 일괄 SMS 발송을 진행하도록 하겠습니다.
