### ISSUE TITLE
kakao open graph 

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#86]
- 카카오톡 오픈 그래프 소스 알아보고 해결하기

**Comment by takearest118** [comment]
@youlim90 url, type 추가하니 잘 동작하네요
> https://github.com/rjkorea/orange/commit/7655d2c141f109ebb39bd6b790ed8119ebfd535f

**Comment by takearest118** [comment]
페이스북 디버거
> https://developers.facebook.com/tools/debug/

카카오 캐시툴
> https://developers.kakao.com/docs/cache

**Comment by youlim90** [comment]
@takearest118 감사하무니다 아리가또고자이마스
