### ISSUE TITLE
행사준비 품목(the final count down)

### ISSUE THREAD

**Issue by youlim90** [rjkorea/avocado#95]
행사 전 준비품목입니다 [grace]

 - [x] 아이패드 거치대 x 2 (51,800원)

 - [x] 단체복 , 디자인 최종버전 맨투맨 x 5 / 반팔 티셔츠 x 5 (260,000원)

 - [x] 행사장 부스 Back wall / table 디자인 (윤실장님과 제작소 협의 후 결정)

**Comment by youlim90** [comment]
@takearest118  @rj-kelly-kim  

 - 단체복 주문완료/배송중
 - 테이블 제작의뢰 완료/백월 월요일 시안 전달

**Comment by rj-kelly-kim** [comment]
현금(캐시) 박스도 1개 준비 부탁 드립니다.

**Comment by youlim90** [comment]
캐쉬박스 15400원 주문/결제 완료

**Comment by youlim90** [comment]
테이블 시안 전달 완료

**Comment by youlim90** [comment]
12/26 단체티 재제작 (목요일 홍대매장 픽업)
12/27 back wall 시안전달완료.

**Comment by youlim90** [comment]
- TKIT로고 수제 캔디 주문완료 (410,000원)
 - 미니 배너 제작(by Grace)

**Comment by youlim90** [comment]
- 사탕 포장 재료 및 DP케이스 준비 완료
