### ISSUE TITLE
'발권 티켓' 추가 인증 처리

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#97]
구글 드라이브로 등록 되고 있는 초대권 정보 중
[발권 티켓] sheet 의 내용이 확인 되었습니다. 

## 1. 발권 티켓 의 정의
사전 종이로 초대권을 공유한 형태를 '발권 티켓'이라 함

## 2. 발권 티켓의 유형(타입)
2.1 환경부담금이 없는(X) 종이 초대권
2.2 환경부담금이 있는(O) 종이 초대권

## 3. 발권 티켓 수량
582 장

## 4. 고려 사항
고객정보를 입력하고 처리하기에 발권 티켓의 수량이 많음
한 사람당 기본 Default 정보 (이름, 전화번호)만 입력 받아도 트래픽 증가의 원인이 됨

## 5.  TKIT 처리 프로세스
@takearest118 아래 예시로 프로세스 잡아 봅니다. 

5.1 Invitation Type 에 종이 초대권 추가 생성
     ex) 30일_발권(일반) /  31일_발권(일반)

5.2 Entrance 메뉴 내 [발권 티켓] 버튼 생성
      -> 해당 [발권 티켓]버튼을 누를 시, gender / fee / fee method 정보만 입력(확인)하고 Entrance 처리 완료

이상 내용 공유 드리며,
@takearest118 '발권티켓' 처리 방식에 대해 확인 부탁 드려요

**Comment by takearest118** [comment]
@rj-kelly-kim @youlim90
5.2 Entrance 메뉴에서 입장객이 아이패드를 통해서
DB에 존재하지 않는 전화번호를 입력했을 경우
발권 처리용 폼을 표시해서 처리하는 방법도 괜찮을 것 같아요 :)

**Comment by rj-kelly-kim** [comment]
오! 좋습니다~!
그럼 발권 티켓으로 entrance 가 처리 된 고객 정보는  
- mobile_number
- gender
- fee
- fee method 
가 되는 거겠죠?

**Comment by rj-kelly-kim** [comment]
해당 발권 티켓은
TKIT 시스템 인증을 거치지 않고
현장 신분증을 통한 성인 인증 정보만 확인 후
밴딩 처리 와 환경부담금 결제 진행으로 프로세스를 정리 하겠습니다.
