### ISSUE TITLE
[업무요청] Admin 외부 계정 생성 건 (VU Ent.)

### ISSUE THREAD

**Issue by rj-kelly-kim** [rjkorea/avocado#98]
VU Ent. 의 T KIT Admin 접근 계정을 아래와 같이 생성 요청 드립니다. 

- ID : han@vuent.co.kr  
- PW : *********
- 접근 권한 : Admin ALL

**Comment by takearest118** [comment]
@rj-kelly-kim 생성했습니다.

**Comment by takearest118** [comment]
@rj-kelly-kim 암호는 보안상 별표처리 했습니다.
